---
title: "Tidy Data Lab"
author: "Jose Bravo"
date: "March 13, 2017"
output: html_document
---

#Manipulating Data with dplyr

##Loading the data provided by swirl. 
```{r, echo=FALSE}
library(dplyr)
library(tidyr)
library(readr)
library(lubridate)
path2csv <- "C:\\Users\\jbravo\\Documents\\R\\win-library\\3.3\\swirl\\Courses\\Getting_and_Cleaning_Data\\Manipulating_Data_with_dplyr\\2014-07-08.csv"
mydf <- read.csv(path2csv, stringsAsFactors = F)
```

```{r}
#List dimensions of the dataframe and preview it. 

dim(mydf)
head(mydf)
```

```{r}
#Create a data frame tbl
cran <- tbl_df(mydf)
```


```{r}
#The five 'verbs' that cover most fundamental data manipulation
select(cran, ip_id, package, country)
```

```{r}
#print the variables r_arch to county
select(cran, r_arch:country)
# or in reverse
select(cran, country:r_arch)
# print all the variables in the dataframe except time 
select(cran, -time)
# omit all variables from X to size
select(cran, -(X:size))
```

```{r}
# Using filter() to select subset of rows
filter(cran, package == "swirl")
# You can specify many conditions 
filter(cran, r_version == "3.1.1", country == "US")
# Alter the previous command but specify India, and r versions less than 3.0.8
filter(cran, r_version <= "3.0.2", country == "IN")
# Filter can also take boolean operators 
filter(cran, country == "US" | country == "IN")
# can also filter numeric values
filter(cran, size > 100500, r_os == "linux-gnu")
# filter out NAs from the r_version variable
filter(cran, !is.na(r_version))
```

```{r, echo=FALSE}
cran2 <- select(cran, size:ip_id)
```

```{r}
#using arrange()
arrange(cran2, ip_id)
# now in descending order
arrange(cran2, desc(ip_id))
# arrange multiple variables
arrange(cran2, country, desc(r_version), ip_id)
```

```{r, echo = FALSE}
cran3 <- select(cran, ip_id, package, size)
```

```{r}
# Using the mutate() function to add additional column
mutate(cran3, size_mb = size / 2^20)
# add one more column of size_gb
mutate(cran3, size_mb = size / 2^20, size_gb = size_mb / 2^10)
# add another column with the correct size of the package
mutate(cran3, correct_size = size + 1000)
```

##Grouping and Chaining with dplyr

```{r}
#Using group_by function
by_package <- group_by(cran, package)
# summarize by mean(size)
summarize(by_package, mean(size))

# modifying swirl script 
pack_sum <- summarize(by_package, count = n(), unique = n_distinct(ip_id), countries = n_distinct(country), avg_bytes = mean(size))


# print pack_sum
pack_sum

# print the one percentile of the pack_sum
quantile(pack_sum$count, probs = 0.99)

top_counts <- filter(pack_sum, count > 679)
top_counts

# Using arrange to sort top_counts into new variable top_counts_sorted
top_counts_sorted <- arrange(top_counts, desc(count))

#view the data
View(top_counts_sorted)

# Apply filter to pack_sum to select all rows corresponding to values of 'unique' that are strictly greater than 465. Assign the result to a object called top_unique.
top_unique <- filter(pack_sum, unique > 465)

#Now arrange() top_unique by the 'unique' column, in descending order
top_unique_sorted <- arrange(top_unique, desc(unique))
```

```{r} 
# The following code is completing the scripts that Swirl() has generated for the user to complete.
# chain1.R completed
cran %>%
  select(ip_id, country, package, size) %>%
	print

# chain2.R completed
cran %>%
  select(ip_id, country, package, size) %>%
  mutate(size_mb = size / 2^20)

# chain3.R completed
cran %>%
  select(ip_id, country, package, size) %>%
  mutate(size_mb = size / 2^20) %>%
  # Your call to filter() goes here
  filter(size_mb <= 0.5)

# chain4.R
cran %>%
  select(ip_id, country, package, size) %>%
  mutate(size_mb = size / 2^20) %>%
  filter(size_mb <= 0.5) %>%
  # Your call to arrange() goes here
  arrange(desc(size_mb))

```

##Tidying Data with tidyr 
```{r}
# unfortunately, these courses are bugged within markdown, so I have to create the dataframes myself
grade <- c("A","B","C","D","E")
male <- c(1,5,5,5,7)
female <- c(5,0,2,5,4)
students <- data.frame(grade, male, female)
# Print the data frame students
students
# call gather() with the following arguments (in order):students, sex, count, -grade
gather(students, sex, count, -grade)


male_1 <- c(3,6,7,4,1)
female_1 <- c(4,4,4,0,1)
male_2 <- c(3,3,3,8,2)
female_2 <- c(4,5,8,1,7)
students2 <- data.frame(grade, male_1, female_1, male_2, female_2)

# Print students2
students2

#Call gather() with the following arguments (in order): students2, sex_class, count, -grade). Store the result in a variable called res.
res <- gather(students2, sex_class, count, -grade)
res

# Call separate() on res to split the sex_class column into sex and class.
separate(res, col = sex_class, into = c("sex", "class"))

# Completing the generated Swirl() scripts.
# script1.R complete
students2 %>%
  gather(sex_class ,count ,-grade ) %>%
  separate( col = sex_class, into = c("sex", "class")) %>%
  print

name <- c("Sally", "Sally", "Jeff", "Jeff", "Roger", "Roger", "Karen","Karen", "Brian","Brian")
test <- c("midterm","final","midterm","final","midterm","final","midterm","final","midterm","final")
class1 <- c("A","C",NA,NA,NA,NA,NA,NA,"B","B")
class2 <- c(NA,NA,"D","E","C","A",NA,NA,NA,NA)
class3 <- c("B","C",NA,NA,NA,NA,"C","C",NA,NA)
class4 <- c(NA,NA,"A","C",NA,NA,"A","A",NA,NA)
class5 <- c(NA,NA,NA,NA,"B","A",NA,NA,"A","C")
students3 <- data.frame(name, test,class1,class2,class3,class4,class5)

# print students3
students3

# script2.R complete
students3 %>%
  gather( class,grade , class1:class5 , na.rm= TRUE) %>%
  print

# script3.R complete
# a call to spread(), which will allow us to turn the
# values of the test column, midterm and final, into
# column headers (i.e. variables).
students3 %>%
  gather(class, grade, class1:class5, na.rm = TRUE) %>%
  spread( test, grade ) %>%
  print

# We want the values in the class columns to be
# 1, 2, ..., 5 and not class1, class2, ..., class5.
#
# Use the mutate() function from dplyr along with
# parse_number(). Hint: You can "overwrite" a column
# with mutate() by assigning a new value to the existing
# column instead of creating a new column.
# script4.R complete
students3 %>%
  gather(class, grade, class1:class5, na.rm = TRUE) %>%
  spread(test, grade) %>%
  mutate(class = parse_number(class)) %>%
  print

#
id <- c(168,168,588,588,710,710,731,731,908,908)
name <- c("Brian","Brian","Sally","Sally","Jeff","Jeff","Roger","Roger","Karen","Karen")
sex <- c("F","F","M","M","M","M","F","F","M","M")
class <- c(1,5,1,3,2,4,2,5,3,4)
midterm <- c("B","A","A","B","D","A","C","B","C","A")
final <- c("B","C","C","C","E","C","A","A","C","A")
students4 <- data.frame(id,name,sex,class,midterm, final)

#
# script5.R completed
student_info <- students4 %>%
  select( id, name, sex ) %>%
  print

# script6.R completed
student_info <- students4 %>%
  select(id, name, sex) %>%
  unique %>%
  print

# script7.R completed
gradebook <- students4 %>%
  select(id, class, midterm, final) %>%
  print

```

```{r}
# Again, I have to create the dataframes myself because markdown and swirl variables don't play nice
name <- c("Brian","Roger","Roger","Karen")
class <- c(1,2,5,4)
final <- c("B","A","A","A")
passed <- data.frame(name,class,final)

name <- c("Brian","Sally","Sally","Jeff","Jeff","Karen")
class <- c(5,1,3,2,4,3)
final <- c("C","C","C","E","C","C")
failed <- data.frame(name,class,final)


#Use dplyr's mutate() to add a new column to the passed table.
passed <- passed %>% mutate(status = "passed")
# Now, do the same for the failed table
failed <- failed %>% mutate(status = "failed")

#Call bind_rows() with two arguments, passed and failed (in that order), to join the two tables.
bind_rows(passed, failed)


##
score_range <- c("700-800","600-690","500-590","400-490","300-390","200-290")
read_male <- c(40151,121950,227141,242554,113568,30728)
read_fem <- c(38898, 126084, 259553,296793,133473,29154)
read_total <- c(79049, 248034, 486694, 539347, 247041, 59882)
math_male <- c(74461, 162564, 233141,204670, 82468,18788)
math_fem <- c(46040, 133954, 257678,288696,131025,26562)
math_total <- c(120501,296518,490819,493366,213493,25350)
write_male <- c(31574, 100963, 202326, 262623, 146106, 32500)
write_fem <- c(39101, 125368, 247239, 302933, 144381, 24933)
write_total <- c(70675, 226331, 449565, 565556, 290481, 57433)
sat <- data.frame(score_range,read_male,read_fem, read_total, math_male,math_fem, math_total, write_male, write_fem, write_total)

##

# script8.R completed
sat %>%
  select(-contains("total")) %>%
  gather(part_sex, count, -score_range) %>%
  separate(part_sex, c("part","sex")) %>%
  print

# script9.R completed
sat %>%
  select(-contains("total")) %>%
  gather(part_sex, count, -score_range) %>%
  separate(part_sex, c("part", "sex")) %>%
  group_by(part,sex) %>%
  mutate(total = sum(count),
         prop = count / total
  ) %>% print
```

##Dates and Times with lubridate
```{r}
# print today() and put it in variable this_day
this_day <- today()

# use other time functions
year(this_day)
wday(this_day)
wday(this_day, label = TRUE)

# lubridate also records date and time combinations
this_moment <- now()
hour(this_moment)

my_date <- ymd("1989-05-17")
my_date 
ymd("1989 May 17")
mdy("March 12, 1975")
dmy(25081985)

update(this_moment, hours = 8, minutes = 34, seconds = 55)
this_moment <- update(this_moment, hours = 10, minutes = 16, seconds = 0)

nyc <- now("America/New_York")
depart <- nyc + days(2)
depart <- update(depart, hours = 17, minutes = 34)
arrive <- depart + hours(15) + minutes(50)
arrive <- with_tz(arrive, "Asia/Hong_Kong")

last_time <- mdy("June 17, 2008", tz = "Singapore")
how_long <- interval(last_time, arrive)
as.period(how_long)

```